### PR TITLE
Fix 219

### LINKED ISSUE #219: Feature: Validate & Prepare Data on Load
## Feature Details
As a gsm.app user, in order to use the app speedily and without crashes, I'd like the data to be checked and prepared when the app launches (not when each user accesses the data).

## Possible Implementation
Given the reality that Shiny servers tend to sleep when they aren't in use, don't go overboard with this.  Consider doing a bit of a hybrid, where the data gets pivoted as needed the first time a user touches it, and then cached for all users. [bind_cache()](https://shiny.posit.co/r/articles/improve/caching/) should work well for this route.

### LINKED ISSUE #227: UI: Full Screen view of tables
## UI Details

Allow users to expand tables to full-screen view for all cards containing deep dive tables

### PR DESCRIPTION
**Pull request by jonthegeek**
## Overview
Validate inputs.
Set up purely UI things (non-reactive) in the UI whenever possible.
Other general cleanup to better make use of data.

## Connected Issues
- Closes #219.
- Closes #227.
- Related to #158

### CODE REVIEW

File: R/data_Validate.R [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+      ),
+      class = "gsm.app-error-invalid_input"
+    )
+  }
+  return(df)
+}
+
+## df-specific Validation Functions ----
+
+validate_dfResults <- function(dfResults) {
```
Comment (lauramaxwell) [inline R/data_Validate.R:52]: for these functions, i agree that it makes sense to have fixed required columns at the moment, but is there a future state where adding additional optional modules/tabs to the app would require a different set of required columns? in which case, having a `chrRequiredColumns` with defaults set to the current set of columns. Not anything necessary at the moment- and maybe too much future-proofing, but just thought i'd raise the point while i'm reviewing this.

**Review by lauramaxwell — APPROVED** [review]
One comment in the code that is not a blocker, just thinking about further use cases. 

Also, as I was checking app functionality on this branch, it appears that the Site and Participant drop downs in the sidebar aren't properly linked. When I select a site, it does not filter to a set of participants, and when i select a participant, the site they are a member of does not get selected. I think it would be helpful if those fields were accurately linked. Not related to the content of this PR, but wanted to make sure that this bug was on your radar.

File: R/data_Validate.R (hunk 1 above)
Comment (jonthegeek) [reply R/data_Validate.R:52]: I think this app will have requirements, even if those requirements might change; we can explicitly change the list inside the function when they do. Once we have some of this information in workflows, though, it MIGHT make sense to check there so everything is logged in one place. Mostly I want to make sure we aren't just counting on people to use our preferred method of deploying things, and then crashing downstream when they don't use that method and something is weird.
