### PR TITLE
Protect against NA names

### LINKED ISSUE #432: Bugfix: Navbar header and webpage title display `NA` for studies without a nickname
## Expected Behavior
Navbar header and webpage title should display study ID with study nickname in parentheses, if non-missing.

## Current Behavior
Only nickname is displayed, even when non-missing.

## Steps to Reproduce

1.
2.
3.
4.

### PR DESCRIPTION
**Pull request by jonthegeek**
## Overview
Protect against NA names in the title. I also made a tiny unrelated tweak in `R/mod_PrevalencePlots.R` to deal with a slight change in ggplot2, and several screenshots changed imperceptibly related to that change.

## Test Notes/Sample Code
Since this does not impact any acceptance requirements of actual business requirements, it is being unit-tested, but not specifically included in the qualification suite.

## Connected Issues

- Closes #432.

### CODE REVIEW

File: R/utils.R [hunk 1]
```diff
@@ -133,14 +133,26 @@ MakeParamLabelsChr <- function(chrParams, lParamLabels = NULL) {
...
-    dfStudy$Value[tolower(dfStudy$Param) == "protocol_title"] %||%
-    dfStudy$Value[tolower(dfStudy$Param) == "studyid"] %||%
+  dfStudy <- FilterBy(
+    dfGroups[!is.na(dfGroups$Value), ],
+    "Study",
+    "GroupLevel"
+  )
+
+  appTitle <- dfStudy$Value[tolower(dfStudy$Param) == "nickname"] %|0|%
+    dfStudy$Value[tolower(dfStudy$Param) == "protocol_title"] %|0|%
```
Comment (samussiah) [inline R/utils.R]: Protocol title is a big old sentence that doesn't make sense here, like

> A Phase 3, Double-Blinded, Multicenter, Randomized Study to Evaluate Safety and Efficacy of Twice Yearly Long-Acting Subcutaneous Lenacapavir, and Daily Oral Emtricitabine/Tenofovir Alafenamide for Pre-Exposure Prophylaxis in Adolescent Girls and Young Women at Risk of HIV Infection

If `nickname` doesn't exist this should just fall back on `dfGroups$GroupID` where `GroupLevel == 'Study'`.

**Review by samussiah — CHANGES_REQUESTED** [review]
Defaulting to study ID when `nickname` is `NA` is exactly what we want here. Only concern is `nickname` is an arbitrary parameter name and is not transparent to the app developer.

The most concrete approach is to just grab `GroupID` where `GroupLevel=='Study'` from `dfGroups` and let the user overwrite it with the `strTitle` argument in their deployment, but including the `nickname` lookup doesn't hurt.

File: R/utils.R (hunk 1 above)
Comment (jonthegeek) [inline R/utils.R]:
```suggestion
    dfStudy$GroupID[[1]] %|0|%
```

**Review by samussiah — APPROVED** [review]
