### PR TITLE
Refined Selection in Widget Plots

### LINKED ISSUE #301: Bugfix: Deselect on Initial ScatterPlot Load
## Expected Behavior
Clicking a point to deselect it should deselect it on initial load.

## Current Behavior
This doesn't work the first time (and probably has some other shadiness).

## Steps to Reproduce

1. Load https://openrbqm.shinyapps.io/gsm-app-dev/
2. Click somewhere in the Overview Table. "0X159 (Flores)" (the first column or AE) is an easy one to work with.
3. Note that the site is selected in the Scatter Plot and the site participants shows "Site 0X159" (or whatever you clicked).
4. Click the selected site in the plot.
5. Note that the site participants still shows the previously selected site, and the drop-down hasn't updated.
6. Click the site again, and then again.
7. Note that the site is deselected.

## Possible Solution
I suspect, like I found with gt, we need to return separate values for (effectively) "I don't know the value" versus "The user has deselected the point.

### PR DESCRIPTION
**Pull request by jonthegeek**
## Overview
Differentiate between "nothing selected yet" and "everything deselected" in widget plots.

## Test Notes/Sample Code
I also cleaned up and hopefully stabilized the screenshot tests.

## Connected Issues

- Closes #301.

### CODE REVIEW

**Comment by jonthegeek** [comment]
App deployed at https://openrbqm.shinyapps.io/gsm-app-pr-307/ (but I cut off the first attempt so the bot won't post that).

File: inst/inputs/widgetInputHelpers.js [hunk 1]
```diff
@@ -20,9 +20,13 @@ function findWidget(scope, widgetName) {
 function getWidgetPlotValue(el) {
   const canvas = el.querySelector('canvas');
   if (!canvas || !canvas.chart) {
-    return null;
+    return null; // Not yet initialized
   }
-  return canvas.chart.data.config.selectedGroupIDs;
+  const selectedGroupIDs = canvas.chart.data.config.selectedGroupIDs;
+  if (Array.isArray(selectedGroupIDs) && selectedGroupIDs.length === 0) {
```
Comment (lauramaxwell) [inline inst/inputs/widgetInputHelpers.js:26]: nice, simple fix!

**Review by lauramaxwell — APPROVED** [review]
Working properly according to #301, and super straightforward. Nice work!
